# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 64f518a3de05430e706803c68560c9652a3a9f766abb9126d1bbe07a4627a6ab733c35ea80ec30c593ec7ee7031eeafbe60e1fc9297a119dab7d32735acd08a4

test:
  secret_key_base: 1e7790ae6c503d2a6c339d120b5db5582949c2b3d2bf1bc59421717944e9efba2cd27d41e62e1c3edf372f83e6815cb68c27557aad12b4aaf98036a8b1fb6ca8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
